CREATE TABLE IF NOT EXISTS background_jobs (
    id VARCHAR(100) PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'queued',
    options_json LONGTEXT NOT NULL,
    result_json LONGTEXT NULL,
    errors_json LONGTEXT NULL,
    total INT DEFAULT 0,
    matching_total INT DEFAULT 0,
    scanned INT DEFAULT 0,
    processed INT DEFAULT 0,
    generated_count INT DEFAULT 0,
    reused_count INT DEFAULT 0,
    skipped INT DEFAULT 0,
    failed_count INT DEFAULT 0,
    pages INT DEFAULT 0,
    current_message VARCHAR(500) NULL,
    current_member VARCHAR(255) NULL,
    last_processed_user_id INT DEFAULT 0,
    created_by INT NULL,
    locked_by VARCHAR(120) NULL,
    locked_until DATETIME NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    failed_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_type_status (type, status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
